### ISSUE TITLE
BOINC Roadmap 2020

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#3417]
Reference: [BOINC Roadmap 2019](https://docs.google.com/document/d/1vy36Bvyj4MIqNpfqXHcIQ8xjpxuPpECgqul9BvStvis/edit)

#### Android 10 problem
The current BOINC client doesn’t work on Android 10 because of changes to background process mechanisms.

Related issues:
- [x] #3334: [Android] 7.16.3, Another volunteer app is already running on this device
- [x] #3333: [Android] 7.16.3, doesn't run, always suspended - on batteries
- [x] #2467: BOINC on OnePlus 5 Android 8 stops running by itself after 10 minutes
- [x] #2211: user-reported Android issue

#### Lower VM process priority
Make VMs run at low process priority.  VBox used to have this feature, but now it doesn’t.  Either get them to restore it, or make our own fork of VBox.
This is critical.  Without VM apps, setting up projects is too hard.  Without low priority, VMs degrade computer performance unacceptably.

Related issues:
- [ ] #2785: Run VM apps at low process priority
- [ ] #2273: Windows VirtualBox Process Priority support

#### Eliminate GPU streaming glitches
Goal: eliminate glitches in streaming video playback because of GPU usage

Related issues:
- [ ] #2301: Don't use GPU while watching movie

#### Fan noise
Goal: avoid excessive fan noise

Related issues:
- [ ] #2215: Throttle computing based on fan speeds
- [ ] #1378: CPU temperatures monitoring
- [ ] #1379: GPU Temperature Monitoring
- [ ] #1474: BOINC Monitoring daemon

**Comment by KenSharp** [comment]
Given the vast number of cross-platform containers is Vbox even worth the effort?

The majority of projects that use VMs seem to use Linux as the guest OS. A lot of OS can run Linux apps or kernels natively. There's also UML if a specific kernel is needed. The only outlier might be macOS but they're intentionally making everything difficult. It's a dreadful choice of an OS in this day and age. Even more of a comical system after the recent announcements.

**Comment by CharlieFenton** [comment]
Funny you should mention that. According to [this](https://www.apple.com/newsroom/2020/06/apple-announces-mac-transition-to-apple-silicon/) recent announcement from Apple, on MacOS with the new hardware:
> Virtualization technology allows users to run Linux.

**Comment by tristanolive** [comment]
There's some potential for using WSL on Windows instead of VirtualBox, but it seems you [can't set process priority](https://github.com/Microsoft/WSL/issues/894) with that, either. At a glance, it is also more restrictive, primarily intended for bash usage, and targeted for developer use. That doesn't necessarily mean it's any less stable, but it is something to consider.

I do expect VirtualBox to become less relevant over time, as native container and virtualization support mature on Windows and MacOS. I don't think we're quite there, though; and even then, there may be a solid argument to make in favor of the excellent sandbox that a full VM creates versus running an app quasi-natively with an environment like WSL. For some applications (and some volunteers), that is quite valuable.

**Comment by AenBleidd** [comment]
This roadmap is outdated.
